stages:
  - test
  - build

test:
  stage: test
  image: python:3.6
  script:
    - pip install pipenv
    - pipenv install
    - pipenv run python generate.py
  except:
    - master

pages:
  stage: build
  image: python:3.6
  script:
    - pip install pipenv
    - pipenv install
    - pipenv run python generate.py
    - mv output public
  artifacts:
    paths:
      - public
    expire_in: 3 days
  only:
    - master
